// Copyright 2025 the VizIR Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! HTML report generator for `vizir_charts_demo`.

pub(crate) struct HtmlSection {
    pub(crate) title: &'static str,
    pub(crate) description: &'static str,
    pub(crate) svg: String,
}

pub(crate) fn render_report(title: &str, sections: &[HtmlSection]) -> String {
    let mut out = String::new();
    out.push_str("<!doctype html>\n");
    out.push_str("<html lang=\"en\">\n");
    out.push_str("<head>\n");
    out.push_str("  <meta charset=\"utf-8\" />\n");
    out.push_str("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
    out.push_str(&format!("  <title>{}</title>\n", escape_html(title)));
    out.push_str("  <style>\n");
    out.push_str("    body { font-family: system-ui, -apple-system, sans-serif; margin: 24px; line-height: 1.4; }\n");
    out.push_str("    h1 { margin: 0 0 16px 0; }\n");
    out.push_str("    section { margin: 24px 0 40px 0; }\n");
    out.push_str("    .figure { display: inline-block; border: 1px solid #ddd; padding: 8px; background: white; }\n");
    out.push_str("    svg { display: block; width: 720px; max-width: 100%; height: auto; }\n");
    out.push_str("    code { background: #f6f8fa; padding: 2px 4px; border-radius: 4px; }\n");
    out.push_str("  </style>\n");
    out.push_str("</head>\n");
    out.push_str("<body>\n");
    out.push_str(&format!("  <h1>{}</h1>\n", escape_html(title)));
    out.push_str("  <p>This file is generated by <code>vizir_charts_demo</code>.</p>\n");

    for s in sections {
        out.push_str("  <section>\n");
        out.push_str(&format!("    <h2>{}</h2>\n", escape_html(s.title)));
        if !s.description.is_empty() {
            out.push_str(&format!("    <p>{}</p>\n", escape_html(s.description)));
        }
        out.push_str("    <div class=\"figure\">\n");
        out.push_str(&s.svg);
        out.push_str("    </div>\n");
        out.push_str("  </section>\n");
    }

    out.push_str("</body>\n");
    out.push_str("</html>\n");
    out
}

fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}
